### ISSUE TITLE
Auto-generated sreens may be reject on subsequent extension uploads

### ISSUE THREAD

**Issue by radu-stefan-dt** [dynatrace-extensions/dynatrace-extensions-vscode#135]
**Describe the bug**
With our template of auto-generated screens the Actions part is no longer accepted by the cluster on subsequent updates. This is because when using the Global List or Global Header for these actions it is no longer possible to specify the HEADER location.

All such snippets:

```yaml
    actions: 
      - actionScope: GLOBAL_LIST
        actionLocation: HEADER
        actions: 
          - actionExpression: hubExtension|extensionId=custom:cegeka.training.one.radu|text=configure
            visualization:
              iconOnly: false
              icon: options-menu
              displayName: Configure extension
      - actionScope: GLOBAL_DETAILS
        actionLocation: HEADER
        actions: 
          - actionExpression: hubExtension|extensionId=custom:cegeka.training.one.radu|text=configure
            visualization:
              iconOnly: false
              icon: options-menu
              displayName: Configure extension
```

Must be updated to remove "actionLocation"
