### ISSUE TITLE
SNMP table entry OID incorrectly detected as static

### ISSUE THREAD

**Issue by Dynatrace-James-Kitson** [dynatrace-extensions/dynatrace-extensions-vscode#145]
**Describe the bug**
When using [this OID](https://oid-rep.orange-labs.fr/get/1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.2) in a table subgroup validation detects it to be a static value and marks it as an error.

`Type conflict. This OID is static but being used inside a 'table' subgroup.`

**Steps to reproduce**
Use the yaml snippet provided below in an extension workspace. The error will be for OID used in the 'description' dimension.

**Expected behavior**
No validation error

**Screenshots or YAML snippet**

```yaml
snmp:
  - group: test
    interval:
      minutes: 1
    subgroups:
      - subgroup: table-test
        table: true
        dimensions:
          - key: description
            value: oid:1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.2
        metrics:
          - key: value
            value: oid:1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3
```
