### ISSUE TITLE
Better extension starter templates

### ISSUE THREAD

**Issue by radu-stefan-dt** [dynatrace-extensions/dynatrace-extensions-vscode#174]
# Improvement: Better extension templates

## Context

Currently when starting a new extension we provide an overly simplistic yaml:
```yaml
name: custom:my.awesome.extension
version: "0.0.1"
minDynatraceVersion: "1.256.0"
author:
  name: Your Name Here
```

In addition, our very popular [Generic Database Queries extension](https://www.dynatrace.com/hub/detail/custom-database-queries) is now deprecated along with the whole EF1 framework and will later be completely unavailable. There is no direct replacement (e.g. like-for-like extension) but users can leverage SQL datasources to create extensions that run their desired queries.

At this point users are left with very little detail on how to actually start writing the datasource part of the extension. We have documentation online, but we could also start them in a better way.

## Details

For Databases we can probably draft up a generic definition for topology - DB Host, Instance, runs on `dt.entity.host` etc. Along with that screens are probably self-deduceable too. Create the base screens similar to how we do already, and maybe add some injections for the Host.

However, for new users of any datasource, we could provide them with some basic YAML enough to give a hint on how to extract metrics/dimensions etc.

This is an example from a sql-like datasource, but something similar can be done for all:

```yaml
sql:
  - group: my-queries
    subgroups:
      - subgroup: first-query
        query: >
          "Write your first query here"
        dimensions:
          - key: example.dimension
            value: col:COLUMN_NAME_1
        metrics:
          - key: example.metric
            value: col:COLUMN_NAME_2
```

## Use Cases
- Help users transition from deprecated extension
- Simplify the work with custom database extensions
- Increase adoption of SQL datasource

## Challenges
- Translating query output into metrics and dimensions may not be very straightforward
- The starter template is valuable, but the v1 config conversion has a timer on it as it will only be valuable if users have time to use it (current hard deprecation deadline Oct 2024).
