### ISSUE TITLE
[Bug]: Build command fails when using single quotes

### ISSUE THREAD

**Issue by radu-stefan-dt** [dynatrace-extensions/dynatrace-extensions-vscode#252]
### Description

When using single quotes (`'`) for the `name` and `version` attributes of the extension manifest, the regex that's checking these part of the build command will fail to read the value correctly.

Sample manifest:

```yaml
name: custom:myextension
version: '1.0.0'
minDynatraceVersion: 1.300.0
author:
  name: me
```

### Steps to reproduce

1. Write an extension manifest where the name or version are surrounded by single quotes `'`
2. Run the build command
3. Hit the error. The message says that either the name or version are missing from the manifest.

### Support information

- [ ] Screenshots
- [X] Extension manifest file
- [ ] YAML snippets
- [X] Support archive ([see here](https://developer.dynatrace.com/extensions-v2/dynatrace-extensions-vscode/troubleshooting/#collect-a-log-archive))
